# Testing with conda - heavier than the PIP version,
# this includes different engines and plugins

name: Tests with Conda

on: [ push ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    env:
      python-version: "3.8"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python-version }}

      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH

      - name: Install Dependencies from Conda
        run: conda env update --file=devtools/conda-envs/latest.yaml --name=base

      - name: Install geomeTRIC
        run: |
          python setup.py develop --no-deps

      - name: pytest
        run: |
          pytest -v --cov=geometric  geometric/tests/

      - name: Codecov upload
        uses: codecov/codecov-action@v1
        with:
          flags: unittests-conda
          fail_ci_if_error: true
          verbose: true