# Testing with packages that are available from PIP
# this is faste than the tests needing conda

name: Tests with Pip

on: [ push ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.7 ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies with PIP
        run: |
          pip install numpy networkx six rdkit pytest pytest-cov

      - name: Install geomeTRIC
        run: |
          python setup.py develop --no-deps

      - name: pytest
        run: |
          pytest -v --cov=geometric  geometric/tests/

      - name: Codecov upload
        uses: codecov/codecov-action@v1
        with:
          flags: unittests-pip
          fail_ci_if_error: true
          verbose: true